describe('Index Page', () => {
  it('Index Page Navigation', () => {
    cy.visit('/')
    cy.title().should('eq', 'Chris Otto | Father, Developer, Test Engineer')
    cy.get('button[aria-label="scroll"]').click()
  })
  it('Posts are rendered', () => {
    cy.get('#post-list').should('be.visible')
    cy.get('#post-list>li').should('be.visible')
    cy.get('#post-list>li>.link>.gatsby-image-outer-wrapper')
      .first()
      .should('be.visible')
    cy.get('#post-list>li>.link>div')
      .first()
      .should('be.visible')
    cy.get('#post-list>li>.link>p')
      .first()
      .should('be.visible')
      .next()
      .should('be.visible')
  })
  it('Footer Post Navigation', () => {
    cy.get('footer').scrollIntoView()
    cy.get('#post-page-list').should('be.visible')
    cy.get('#post-page-list>li').should('be.visible')
  })
  it('Social Links', () => {
    cy.get('.social').should('be.visible')
    cy.get('.social')
      .find('a')
      .should('have.length', 5)
    cy.get('.social>a')
      .first()
      .should('have.attr', 'title', 'dev')
      .next()
      .should('have.attr', 'title', 'github')
      .next()
      .should('have.attr', 'title', 'instagram')
      .next()
      .should('have.attr', 'title', 'linkedin')
      .next()
      .should('have.attr', 'title', 'twitter')
  })
})
